import LinkedList from './LinkedList.js';

console.log(LinkedList.contains('test'), LinkedList.contains('test3'));
console.log(LinkedList.find('test'), LinkedList.find('test3'));
LinkedList.append('test');
LinkedList.append('test2');
LinkedList.append('test3');
console.log(LinkedList.getHead());
LinkedList.prepend('pre test');
console.log(LinkedList.getHead());
console.log(LinkedList.getTail());
console.log(LinkedList.getSize());
console.log(LinkedList.at(2));
LinkedList.pop();
console.log(LinkedList.getTail());
console.log(LinkedList.contains('test'), LinkedList.contains('test3'));
console.log(LinkedList.find('test'), LinkedList.find('test3'));
console.log(LinkedList.toString());
LinkedList.insertAt('test insert', 1);
console.log(LinkedList.toString());
LinkedList.removeAt(2);
console.log(LinkedList.toString());
